name: /Users/lucasedmundo/Documents/Github/MLET-Phase-3/envs
channels:
  - defaults
dependencies:
  - appnope=0.1.4=py311hca03da5_0
  - asttokens=3.0.0=py311hca03da5_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - comm=0.2.3=py311hca03da5_0
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=py311hca03da5_0
  - executing=2.2.1=py311hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - ipykernel=6.31.0=py311h7eb115d_0
  - ipython=9.7.0=py311hca03da5_0
  - ipython_pygments_lexers=1.1.1=py311hca03da5_0
  - jedi=0.19.2=py311hca03da5_0
  - jupyter_client=8.6.3=py311hca03da5_1
  - jupyter_core=5.9.1=py311hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h897f8a9_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.2.1=py311hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py311hca03da5_1
  - parso=0.8.5=py311hca03da5_0
  - pexpect=4.9.0=py311hca03da5_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py311hca03da5_0
  - prompt-toolkit=3.0.52=py311hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py311hca03da5_0
  - pygments=2.19.2=py311hca03da5_0
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - pyzmq=27.1.0=py311h5a8c52c_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=py311hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.4=py311haa24f5a_0
  - traitlets=5.14.3=py311hca03da5_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - wcwidth=0.2.14=py311hca03da5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - imbalanced-learn==0.14.1
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lightgbm==4.6.0
      - matplotlib==3.10.8
      - numpy==2.4.0
      - pandas==2.3.3
      - pillow==12.1.0
      - pyparsing==3.3.1
      - pytz==2025.2
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - sklearn-compat==0.1.5
      - threadpoolctl==3.6.0
      - tzdata==2025.3
      - xgboost==3.1.2
prefix: /Users/lucasedmundo/Documents/Github/MLET-Phase-3/envs
